# practice_agent/router.py
# ─────────────────────────────────────────────────────────────────────
# FastAPI router for Path B — Practice Agent.
#
# This module is the HTTP boundary for the Practice Agent agentic path.
# It handles two endpoints that together implement a stateful MCQ loop:
#
#   POST /api/practice/start
#     Invokes the LangGraph from the "generate_question" entry point.
#     Persists the generated question (including correct_option) to
#     PostgreSQL so the /answer endpoint can retrieve it.
#     Returns the MCQ to the client (WITHOUT correct_option).
#
#   POST /api/practice/answer
#     Retrieves the session and question from PostgreSQL.
#     Invokes the LangGraph from the "evaluate_answer" entry point.
#     Evaluates the student's answer, optionally triggers Deep_Dive_Tool,
#     persists the completed turn, and returns the outcome + explanation.
#
# Two-request pattern (educational note):
#   Unlike Path A where the entire graph runs in one HTTP request, Path B
#   demonstrates a stateful workflow split across two requests.  The client
#   holds session_id and question_id between requests; the backend stores
#   the server-side state (correct_option, question_text, options) in
#   PostgreSQL between the two calls.  This is a common pattern in
#   production agentic systems where long-running workflows must be
#   checkpointed and resumed.
#
# The LangGraph is compiled once at module load time (_graph) so the
# graph structure is validated at startup rather than on the first request.
#
# Satisfies Req 7.1 (POST /api/practice/start returns MCQ),
#           Req 7.2 (POST /api/practice/answer evaluates answer).
# ─────────────────────────────────────────────────────────────────────
import logging

from fastapi import APIRouter, HTTPException

from database import get_session
from models.api_models import (
    PracticeAnswerRequest,
    PracticeAnswerResponse,
    PracticeStartRequest,
    PracticeStartResponse,
)
from models.db_models import PracticeSession
from practice_agent.graph import build_practice_graph

logger = logging.getLogger(__name__)

# ── FastAPI router ────────────────────────────────────────────────────
# prefix="/api/practice" means all routes defined below are reachable at
# /api/practice/<path>.  The tag groups them in the OpenAPI docs UI.
router = APIRouter(prefix="/api/practice", tags=["practice_agent"])

# ── Compiled LangGraph singleton ──────────────────────────────────────
# build_practice_graph() constructs and compiles the graph exactly once
# when this module is first imported (at application startup via main.py).
# Compiling validates the graph topology and pre-allocates internal state,
# so subsequent invocations are fast.
#
# Students can inspect the graph structure by calling:
#   print(_graph.get_graph().draw_ascii())
_graph = build_practice_graph()

logger.info("practice_agent graph compiled and ready")


# ── POST /api/practice/start ──────────────────────────────────────────
@router.post("/start", response_model=PracticeStartResponse)
async def start_practice(request: PracticeStartRequest) -> PracticeStartResponse:
    """
    Generate a new multiple-choice question and start a practice session.

    This endpoint invokes the Practice Agent LangGraph from the default
    "generate_question" entry point.  The graph runs generate_question_node
    and then halts at END, returning the MCQ to the client.

    After the graph completes, the generated question (including the
    server-side correct_option) is persisted to PostgreSQL as a "pending"
    history entry.  The /answer endpoint retrieves this entry to evaluate
    the student's answer without requiring a second LLM call.

    The correct_option is NOT included in the response — it is kept
    server-side to prevent the client from trivially determining the answer.

    Args:
        request: Validated PracticeStartRequest containing topic and
                 difficulty_level.

    Returns:
        PracticeStartResponse with session_id, question_id, question_text,
        and four answer options.

    Raises:
        HTTPException 500: If the LangGraph invocation fails unexpectedly.
    """
    # Build the initial state for the generate_question entry point.
    # Fields populated by nodes are initialised to safe empty values.
    initial_state = {
        "session_id": "",           # Generated by generate_question_node
        "question_id": "",          # Generated by generate_question_node
        "topic": request.topic,
        "difficulty_level": request.difficulty_level,
        "question_text": "",        # Set by generate_question_node
        "options": [],              # Set by generate_question_node
        "correct_option": "",       # Set by generate_question_node (NOT returned to client)
        "selected_option": "",      # Not applicable for /start
        "outcome": "",              # Not applicable for /start
        "explanation": None,        # Not applicable for /start
        "graph_status": "generate_question",
        "history": [],
    }

    logger.info(
        "start_practice | topic=%r difficulty=%s",
        request.topic,
        request.difficulty_level,
    )

    try:
        # Invoke the graph from the default entry point ("generate_question").
        # The graph runs generate_question_node → END and returns the final state.
        final_state = _graph.invoke(initial_state)
    except Exception as exc:
        logger.exception("start_practice | graph invocation failed: %s", exc)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate practice question: {exc}",
        ) from exc

    # Persist the generated question to PostgreSQL so the /answer endpoint
    # can retrieve correct_option and question fields without a second LLM call.
    # We store a "pending" entry in the history with outcome=None to indicate
    # the question has been generated but not yet answered.
    _persist_pending_question(final_state)

    return PracticeStartResponse(
        session_id=final_state["session_id"],
        question_id=final_state["question_id"],
        question_text=final_state["question_text"],
        options=final_state["options"],
        # correct_option is intentionally NOT included in the response.
    )


def _persist_pending_question(state: dict) -> None:
    """
    Persist the generated question to PostgreSQL as a pending history entry.

    This is called by /start after the graph generates the MCQ.  It stores
    the full question state (including correct_option) so the /answer endpoint
    can retrieve it without a second LLM call.

    The entry has outcome=None to indicate it is pending (not yet answered).
    The /answer endpoint's persist_node will overwrite this entry with the
    final outcome and explanation.

    Args:
        state: Final PracticeState from generate_question_node.
    """
    with get_session() as db:
        record = (
            db.query(PracticeSession)
            .filter_by(session_id=state["session_id"])
            .first()
        )

        if not record:
            record = PracticeSession(
                session_id=state["session_id"],
                topic=state.get("topic"),
                difficulty_level=state.get("difficulty_level"),
                history=[],
            )
            db.add(record)

        # Store the pending question entry.  outcome=None marks it as unanswered.
        pending_entry = {
            "question_id": state["question_id"],
            "question_text": state["question_text"],
            "options": state["options"],
            "correct_option": state["correct_option"],  # stored server-side only
            "selected_option": None,
            "outcome": None,        # None = pending (not yet answered)
            "explanation": None,
        }

        record.history = (record.history or []) + [pending_entry]
        db.commit()

    logger.info(
        "start_practice | persisted pending question session=%s question_id=%s",
        state["session_id"],
        state["question_id"],
    )


# ── POST /api/practice/answer ─────────────────────────────────────────
@router.post("/answer", response_model=PracticeAnswerResponse)
async def answer_practice(request: PracticeAnswerRequest) -> PracticeAnswerResponse:
    """
    Evaluate the student's answer and return feedback.

    This endpoint retrieves the session and pending question from PostgreSQL,
    then invokes the Practice Agent LangGraph from the "evaluate_answer"
    entry point.  The graph runs:
      - evaluate_answer_node (always)
      - deep_dive_node (only if outcome == "incorrect")
      - persist_node (always — updates the pending entry with the final outcome)

    The correct_option is retrieved from PostgreSQL (stored during /start)
    rather than accepted from the client, preventing answer manipulation.

    Args:
        request: Validated PracticeAnswerRequest containing session_id,
                 question_id, and selected_option.

    Returns:
        PracticeAnswerResponse with outcome, optional explanation, and
        graph_status ("next_question" or "retry").

    Raises:
        HTTPException 404: If the session or question is not found.
        HTTPException 500: If the LangGraph invocation fails unexpectedly.
    """
    # Retrieve the session from PostgreSQL to recover the pending question state.
    with get_session() as db:
        record = (
            db.query(PracticeSession)
            .filter_by(session_id=request.session_id)
            .first()
        )

    if not record:
        raise HTTPException(
            status_code=404,
            detail=f"Practice session '{request.session_id}' not found. "
                   "Call POST /api/practice/start first.",
        )

    # Find the pending question entry matching the submitted question_id.
    # We search in reverse order so the most recent question is found first.
    history: list = record.history or []
    pending_turn = next(
        (
            t for t in reversed(history)
            if t.get("question_id") == request.question_id
            and t.get("outcome") is None  # pending = not yet answered
        ),
        None,
    )

    if not pending_turn:
        raise HTTPException(
            status_code=404,
            detail=f"Question '{request.question_id}' not found or already answered "
                   f"in session '{request.session_id}'.",
        )

    # Recover the server-side question fields from the pending entry.
    # correct_option was stored during /start and never sent to the client.
    correct_option: str = pending_turn.get("correct_option", "")
    question_text: str = pending_turn.get("question_text", "")
    options: list = pending_turn.get("options", [])

    # Build the state for the evaluate_answer entry point.
    # All PracticeState fields must be present because it is a TypedDict.
    initial_state = {
        "session_id": request.session_id,
        "question_id": request.question_id,
        "topic": record.topic or "",
        "difficulty_level": record.difficulty_level or "",
        "question_text": question_text,
        "options": options,
        "correct_option": correct_option,   # recovered from DB, not from client
        "selected_option": request.selected_option,
        "outcome": "",              # Set by evaluate_answer_node
        "explanation": None,        # Set by deep_dive_node (if incorrect)
        "graph_status": "evaluate_answer",
        "history": history,
    }

    logger.info(
        "answer_practice | session=%s question_id=%s selected=%s",
        request.session_id,
        request.question_id,
        request.selected_option,
    )

    try:
        # Invoke the graph starting from "evaluate_answer".
        # LangGraph's compiled graph supports specifying a custom starting node
        # by passing it as the first key in the state dict that matches a node name.
        # We achieve this by building a sub-graph that starts at evaluate_answer.
        #
        # Implementation note: LangGraph does not natively support re-entering a
        # compiled graph at an arbitrary node without a checkpointer.  For this
        # demo we use a lightweight approach: we build a second compiled graph
        # whose entry point is "evaluate_answer" (see _answer_graph below).
        final_state = _answer_graph.invoke(initial_state)
    except Exception as exc:
        logger.exception("answer_practice | graph invocation failed: %s", exc)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to evaluate answer: {exc}",
        ) from exc

    return PracticeAnswerResponse(
        outcome=final_state["outcome"],
        explanation=final_state.get("explanation"),
        graph_status=final_state["graph_status"],
    )


# ── Answer-path sub-graph ─────────────────────────────────────────────
# LangGraph does not support re-entering a compiled graph at an arbitrary
# node without a persistence checkpointer.  For this demo we compile a
# second, lightweight graph whose entry point is "evaluate_answer".
# This graph handles only the /answer path:
#   evaluate_answer → [deep_dive →] persist → END
#
# Students should note that in production you would use LangGraph's
# built-in SQLite or Redis checkpointer to resume a single graph across
# multiple HTTP requests, rather than maintaining two separate graphs.
def _build_answer_graph():
    """
    Build a compiled LangGraph for the /answer path only.

    Entry point: evaluate_answer
    Topology:
        evaluate_answer ──▶ persist ──▶ END          (outcome == "correct")
        evaluate_answer ──▶ deep_dive ──▶ persist ──▶ END  (outcome == "incorrect")
    """
    from langgraph.graph import END, StateGraph

    from practice_agent.nodes import (
        deep_dive_node,
        evaluate_answer_node,
        persist_node,
    )
    from practice_agent.state import PracticeState

    graph = StateGraph(PracticeState)
    graph.add_node("evaluate_answer", evaluate_answer_node)
    graph.add_node("deep_dive", deep_dive_node)
    graph.add_node("persist", persist_node)

    graph.set_entry_point("evaluate_answer")

    graph.add_conditional_edges(
        "evaluate_answer",
        lambda state: state["outcome"],
        {
            "correct": "persist",
            "incorrect": "deep_dive",
        },
    )
    graph.add_edge("deep_dive", "persist")
    graph.add_edge("persist", END)

    return graph.compile()


# Compile the answer-path graph once at module load time.
_answer_graph = _build_answer_graph()

logger.info("practice_agent answer graph compiled and ready")
