# practice_agent/state.py
# ─────────────────────────────────────────────────────────────────────
# PracticeState is the single shared data structure that flows through
# every node in the Practice Agent LangGraph (Path B).  Defining it as
# a TypedDict gives students a clear, typed contract for what data each
# node can read and must write.
#
# The Practice Agent is a stateful MCQ interaction loop.  Unlike Path A
# (which is a single-turn pipeline), Path B spans two HTTP requests:
#   POST /api/practice/start  — generates a question; graph runs from
#                               "generate_question" entry point
#   POST /api/practice/answer — evaluates the answer; graph resumes from
#                               "evaluate_answer" entry point
#
# The state dict is reconstructed from the client payload on each
# request, so every field needed by downstream nodes must be present.
#
# Satisfies Req 7.8 — the LangGraph state schema is defined as a typed
# TypedDict with comments explaining each field.
# ─────────────────────────────────────────────────────────────────────
from typing import List, Optional, TypedDict


class PracticeState(TypedDict):
    """
    Shared state schema for the Practice Agent LangGraph (Path B).

    Fields are populated progressively across two HTTP requests:
      /start  → generate_question_node populates question_text, options,
                correct_option, question_id, and session_id
      /answer → evaluate_answer_node populates outcome; deep_dive_node
                populates explanation; persist_node writes to PostgreSQL
    """

    # ── Session / identity fields ─────────────────────────────────────

    session_id: str
    # UUID string identifying the practice session.
    # Created by the /start route handler and returned to the client.
    # The client must echo it back in every /answer request so the
    # persist_node can append the turn to the correct PostgreSQL row.

    question_id: str
    # UUID string identifying the current MCQ within the session.
    # Generated by generate_question_node and returned to the client.
    # The client echoes it back in /answer so the backend can correlate
    # the answer with the correct question in the history.

    # ── Question generation fields (set by generate_question_node) ────

    topic: str
    # Math topic for MCQ generation (e.g., "quadratic equations").
    # Supplied by the client in PracticeStartRequest and passed verbatim
    # to MCQ_GENERATION_PROMPT so the LLM generates a relevant question.

    difficulty_level: str
    # Difficulty level for the generated MCQ: "easy" | "medium" | "hard".
    # Validated by the Pydantic model before reaching the graph.
    # Passed to MCQ_GENERATION_PROMPT to control question complexity.

    question_text: str
    # The MCQ question stem as generated by the LLM.
    # Parsed from the LLM's JSON response in generate_question_node.
    # Returned to the client in PracticeStartResponse for display.

    options: List[str]
    # Four answer options in the format ["A) ...", "B) ...", "C) ...", "D) ..."].
    # Parsed from the LLM's JSON response in generate_question_node.
    # Returned to the client so the frontend can render radio buttons.

    correct_option: str
    # The correct answer letter: "A", "B", "C", or "D".
    # Parsed from the LLM's JSON response in generate_question_node.
    # NOT returned to the client — kept server-side to prevent cheating.
    # evaluate_answer_node compares selected_option against this field.

    # ── Answer evaluation fields (set by evaluate_answer_node) ────────

    selected_option: str
    # The student's chosen answer letter: "A", "B", "C", or "D".
    # Supplied by the client in PracticeAnswerRequest.
    # Validated by the Pydantic pattern "^[ABCD]$" before reaching the graph.

    outcome: str
    # Result of the answer evaluation: "correct" | "incorrect".
    # Set by evaluate_answer_node by comparing selected_option to correct_option.
    # The LangGraph conditional edge reads this field to route to either
    # persist_node (correct) or deep_dive_node (incorrect).

    # ── Deep dive field (set by deep_dive_node, only on incorrect) ────

    explanation: Optional[str]
    # Detailed concept explanation generated by deep_dive_tool.
    # Only populated when outcome == "incorrect".
    # None when the student answers correctly (no deep dive needed).
    # Returned to the client in PracticeAnswerResponse for display in
    # the visually distinct yellow panel (Req 11.3).

    # ── Workflow control field ─────────────────────────────────────────

    graph_status: str
    # Describes the LangGraph state after the current request completes.
    # Values:
    #   "generate_question" — initial state before /start is processed
    #   "evaluate_answer"   — state after /start; waiting for /answer
    #   "next_question"     — outcome was correct; ready for a new MCQ
    #   "retry"             — outcome was incorrect; student should retry
    # Returned to the client in PracticeAnswerResponse so the frontend
    # knows whether to show a "Next Question" or "Try Again" button.

    # ── Persistence field ─────────────────────────────────────────────

    history: List[dict]
    # Full turn history for the session, persisted to PostgreSQL.
    # Each entry is a dict:
    #   {question_text, options, correct_option, selected_option,
    #    outcome, explanation (or None)}
    # Append-only — persist_node adds a new entry on every /answer call.
    # Allows the session to be reviewed or resumed later.
