# models/api_models.py
# ─────────────────────────────────────────────────────────────────────
# Pydantic models are the single source of truth for API serialization
# and deserialization across all three agentic paths.
#
# Req 12.1 — All API request and response bodies are defined here as
#             Pydantic models, ensuring a single, consistent mechanism
#             for JSON serialization and deserialization.
#
# Req 12.2 — For all valid request objects, serializing to JSON and
#             deserializing back produces an equivalent object (round-
#             trip integrity). Pydantic guarantees this automatically
#             for all field types used below.
#
# Req 12.3 — When a validation error occurs on an incoming request,
#             FastAPI automatically returns HTTP 422 with field-level
#             error details derived from Pydantic's ValidationError.
#             No additional error-handling code is required at the
#             route level.
# ─────────────────────────────────────────────────────────────────────
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


# ── Path A — Adaptive Tutor ───────────────────────────────────────────

class TutorChatRequest(BaseModel):
    """
    Request body for POST /api/tutor/chat.

    The frontend generates a UUID session_id on component mount and
    reuses it for every turn in the same conversation, allowing the
    backend to append turns to the correct PostgreSQL row.
    """

    session_id: str = Field(
        ...,
        description="UUID identifying the conversation session. "
                    "Generated by the frontend on component mount.",
    )
    query: str = Field(
        ...,
        min_length=1,
        description="The student's math question. Must be non-empty.",
    )
    topic: Optional[str] = Field(
        None,
        description="Optional topic label used to filter ChromaDB retrieval "
                    "(e.g., 'calculus', 'linear algebra'). Omit to search all topics.",
    )


class TutorChatResponse(BaseModel):
    """
    Response body for POST /api/tutor/chat.

    The frontend uses route_taken to display a 'RAG' or 'Direct' badge
    next to each tutor response, making the routing decision visible to
    the student.
    """

    session_id: str = Field(
        ...,
        description="Echo of the request session_id for client-side correlation.",
    )
    response: str = Field(
        ...,
        description="Full LLM response including ## Reasoning and ## Answer sections.",
    )
    route_taken: str = Field(
        ...,
        description="'knowledge_required' (RAG path) or 'direct_answer' (no retrieval).",
    )
    context_chunks: List[str] = Field(
        default_factory=list,
        description="Reranked text chunks passed to the LLM as context. "
                    "Empty list when route_taken is 'direct_answer'.",
    )


# ── Path B — Practice Agent ───────────────────────────────────────────

class PracticeStartRequest(BaseModel):
    """
    Request body for POST /api/practice/start.

    Triggers MCQ generation via the Practice Agent LangGraph. The
    difficulty_level field is validated against a fixed set of values
    to prevent the LLM from receiving unexpected difficulty strings.
    """

    topic: str = Field(
        ...,
        min_length=1,
        description="Math topic for MCQ generation (e.g., 'quadratic equations').",
    )
    difficulty_level: str = Field(
        ...,
        pattern="^(easy|medium|hard)$",
        description="Difficulty level for the generated MCQ. "
                    "Must be exactly 'easy', 'medium', or 'hard'.",
    )


class PracticeStartResponse(BaseModel):
    """
    Response body for POST /api/practice/start.

    Returns the generated MCQ. The frontend renders question_text as the
    question stem and options as four radio-button choices. question_id
    must be included in the subsequent POST /api/practice/answer call.
    """

    session_id: str = Field(
        ...,
        description="UUID for the new practice session. "
                    "Must be passed back in PracticeAnswerRequest.",
    )
    question_id: str = Field(
        ...,
        description="UUID identifying this specific MCQ. "
                    "Must be passed back in PracticeAnswerRequest.",
    )
    question_text: str = Field(
        ...,
        description="The MCQ question stem.",
    )
    options: List[str] = Field(
        ...,
        description="Four answer options in the format ['A) ...', 'B) ...', 'C) ...', 'D) ...'].",
    )


class PracticeAnswerRequest(BaseModel):
    """
    Request body for POST /api/practice/answer.

    The selected_option field is validated to accept only a single
    uppercase letter A–D, matching the option labels in PracticeStartResponse.
    """

    session_id: str = Field(
        ...,
        description="Session UUID returned by POST /api/practice/start.",
    )
    question_id: str = Field(
        ...,
        description="Question UUID returned by POST /api/practice/start.",
    )
    selected_option: str = Field(
        ...,
        pattern="^[ABCD]$",
        description="The student's chosen answer. Must be exactly one of: A, B, C, D.",
    )


class PracticeAnswerResponse(BaseModel):
    """
    Response body for POST /api/practice/answer.

    When outcome is 'incorrect', the explanation field is populated by
    the Deep_Dive_Tool with a detailed concept explanation. The frontend
    renders this in a visually distinct yellow panel (Req 11.3).
    """

    outcome: str = Field(
        ...,
        description="'correct' if the student's answer matched the correct option, "
                    "'incorrect' otherwise.",
    )
    explanation: Optional[str] = Field(
        None,
        description="Deep Dive explanation generated by the Deep_Dive_Tool. "
                    "Only present when outcome is 'incorrect'.",
    )
    graph_status: str = Field(
        ...,
        description="LangGraph state after evaluation: "
                    "'next_question' (correct) or 'retry' (incorrect).",
    )


# ── Path C — Doc-to-Concept Agent ────────────────────────────────────

class DocConceptsResponse(BaseModel):
    """
    Response body for GET /api/docs/{document_id}/concepts.

    Returns all formulas extracted from the uploaded PDF and the
    synthetic worked examples generated for each formula. The frontend
    renders formulas in monospace code blocks and examples in prose
    below each formula (Req 11.6).
    """

    document_id: str = Field(
        ...,
        description="UUID of the processed document.",
    )
    filename: str = Field(
        ...,
        description="Original filename of the uploaded PDF.",
    )
    topic: Optional[str] = Field(
        None,
        description="Topic label supplied by the student at upload time.",
    )
    formulas: List[str] = Field(
        default_factory=list,
        description="List of LaTeX-formatted formula strings extracted from the PDF.",
    )
    examples: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Mapping of each formula string to a list of at least two "
                    "synthetic worked examples: {formula: [example_1, example_2, ...]}.",
    )
    chunk_count: int = Field(
        ...,
        description="Total number of text chunks produced during the chunking step.",
    )
