# doc_to_concept/state.py
# ─────────────────────────────────────────────────────────────────────
# LangGraph state schema for the Doc-to-Concept pipeline (Path C).
#
# DocState is a TypedDict — a plain Python dict at runtime, but fully
# typed for static analysis. LangGraph passes this dict between every
# node in the pipeline, so each node reads the fields it needs and
# returns an updated copy of the state.
#
# The pipeline is linear:
#   parse_node → chunk_node → classify_node → embed_store_node
#   → extract_formulas_node → generate_examples_node → persist_node
#
# Each node adds or transforms one or more fields:
#   parse_node          → sets markdown_text
#   chunk_node          → sets chunks
#   classify_node       → updates chunk_type on each chunk; sets formula_chunks
#   embed_store_node    → (side-effect: writes to ChromaDB; state unchanged)
#   extract_formulas_node → sets formulas
#   generate_examples_node → sets examples
#   persist_node        → (side-effect: writes to PostgreSQL; state unchanged)
#
# Requirement satisfied: 8.1 (DocState TypedDict with all pipeline fields).
# ─────────────────────────────────────────────────────────────────────
from typing import Dict, List, Optional

from typing_extensions import TypedDict


class DocState(TypedDict):
    """
    Shared state dict threaded through every node of the Doc-to-Concept
    LangGraph pipeline.

    LangGraph passes this dict to each node function and merges the
    returned dict back into the running state. Nodes should return only
    the fields they modify; unchanged fields are preserved automatically.
    """

    # ── Identity fields ───────────────────────────────────────────────

    document_id: str
    # UUID generated in the router before the graph is invoked.
    # Used as the primary key in the PostgreSQL `documents` table and
    # as the prefix for ChromaDB chunk IDs so chunks can be traced back
    # to their source document.

    filename: str
    # Original filename of the uploaded PDF (e.g., "calculus_notes.pdf").
    # Stored in PostgreSQL for display in the GET /concepts response.

    topic: Optional[str]
    # Optional subject label supplied by the student at upload time
    # (e.g., "calculus", "linear algebra"). Stored as ChromaDB metadata
    # on every chunk so the Adaptive Tutor can filter by topic.

    # ── Raw input ─────────────────────────────────────────────────────

    pdf_bytes: bytes
    # Raw bytes of the uploaded PDF file, passed from the FastAPI route
    # handler to parse_node. Not persisted — only needed for the parse step.

    # ── Pipeline intermediate values ──────────────────────────────────

    markdown_text: str
    # Markdown string returned by LlamaParse after parse_node runs.
    # Contains the full document content with LaTeX math preserved.
    # Consumed by chunk_node to produce the chunks list.

    chunks: List[dict]
    # List of chunk dicts produced by chunk_node. Each dict has:
    #   - text        : the chunk string
    #   - chunk_index : zero-based position in the document
    #   - chunk_type  : initially "explanation"; updated by classify_node
    #                   to "formula" | "explanation" | "example"
    #   - embedding   : added by embed_store_node (list of floats)
    # Consumed by classify_node, embed_store_node, and extract_formulas_node.

    formula_chunks: List[dict]
    # Subset of chunks whose chunk_type was set to "formula" by classify_node.
    # Passed directly to extract_formulas_node so it only processes the
    # relevant chunks rather than scanning the entire document again.

    # ── Extracted content ─────────────────────────────────────────────

    formulas: List[dict]
    # List of formula dicts extracted by extract_formulas_node. Each dict has:
    #   - formula     : LaTeX-formatted formula string (e.g., "x = (-b ± √(b²-4ac)) / 2a")
    #   - description : one-sentence plain-English description of the formula
    # Consumed by generate_examples_node and persist_node.

    examples: Dict[str, List[str]]
    # Mapping from each formula string to a list of at least two synthetic
    # worked examples generated by generate_examples_node.
    # Structure: {formula_string: [example_1_text, example_2_text, ...]}
    # Persisted to PostgreSQL and returned by GET /api/docs/{id}/concepts.
